-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create conversation_status table
CREATE TABLE IF NOT EXISTS public.conversation_status (
    user1_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    user2_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'denied')),
    action_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user1_id, user2_id)
);

-- Allow public access temporarily for the migration if RLS is enabled on your DB
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated messages" ON public.messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated status" ON public.conversation_status FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
